spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/medtracker?stringtype=unspecified
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        show_sql: true
        ddl-auto: none
  sql:
    init:
      schema-locations: classpath:/schema.sql
      data-locations: classpath:/data.sql
initialData:
  loadFromFile: true
website:
  origin: http://192.168.1.162:5173
  localOrigin: http://localhost:5173
