spring:
  datasource:
    url: jdbc:postgresql://db:5432/${POSTGRES_DB}
    username: postgres
    password: ${POSTGRES_PASSWORD:db-wrz2z}
  jpa:
    properties:
      hibernate:
        ddl-auto: none
        show_sql: true
  sql:
    init:
      mode: always
      schema-locations: classpath:/schema.sql
      continue-on-error: true
initialData:
  loadFromFile: false
