server:
  port: 8080
api:
  url: /api/v1/
token:
  signing:
    key: EBE23F1FD75A89A9355F1A81D194EUEISJDLJg23455jjuriu43387kjksfgjlkiuRDDRTGFDXVRXFBERJLIUMLSIhhYLCISL
spring:
  profiles:
    active: dev
  application:
    name: MedTracker
  jpa:
    generate-ddl: false
    show-sql: true
  sql:
    init:
      mode: always
      continue-on-error: true
initialData:
  loadFromFile: false
website:
  origin: ''
  localOrigin: ''




