api:
  url: /api/v1/
token:
  signing:
    key: EBE23F1FD75A89A9355F1A81D194EUEISJDLJg23455jjuriu43387kjksfgjlkiuRDDRTGFDXVRXFBERJLIUMLSIhhYLCISL
spring:
  application:
    name: MedTracker
  h2:
    console:
      enabled: true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
  sql:
    init:
      schema-locations: classpath:/sql/h2/schema.sql
      data-locations: classpath:/sql/h2/data.sql
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:~/h2DBs/medtracker;AUTO_SERVER=TRUE
initialData:
  loadFromFile: true
website:
  origin: http://192.168.1.162:5173
  localOrigin: http://localhost:5173


